# Generated by Django 4.0.4 on 2022-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issue_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='issuer',
        ),
        migrations.AlterField(
            model_name='issue',
            name='numberofitems',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
