# Generated by Django 4.0.4 on 2022-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0015_alter_issue_numberofitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='numberofitems',
            field=models.IntegerField(default=0),
        ),
    ]
