# Generated by Django 4.0.4 on 2022-06-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0016_item_created_number_alter_issue_numberofitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='madeby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
